# Zero-shot (no training images per class)
experiment_name: "fsl_0shot"
fewshot:
  n_way: 6
  k_shot: 0
  n_query: 15
train:
  epochs: 200
  batch_size: 32
  optimizer:
    type: "sgd"
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0
  scheduler:
    type: "CosineAnnealingLR"
    T_max: 200
    eta_min: 0.000001
  warmup_epochs: 1
  mixed_precision: true
